### ISSUE TITLE
Trigger buzzer on co2 level?

### ISSUE THREAD

**Issue by aseques** [oskrs111/diy-co2-monitor#6]
I just build this project using your great guide, now, my idea was to improve de alerting by adding a buzzer (a bit like in this project https://www.hackster.io/367592/co2-measuring-device-for-determining-air-quality-covid-19-1910ee)
The idea would be to trigger the buzzer (i am planning to add a switch before the buzzer so I can stop it by night) when the ppm goes over 1000 ppp ([font](https://github.com/IoTopenTech/TTNMAD_CO2_FREE))
How difficult would that be?

**Comment by oskrs111** [comment]
Hi, it seems easy to implement using the same or similar buzzer breakout board.
I'll work on folowing days 😉

**Comment by aseques** [comment]
Great, I started fiddling with this myself, but I'ma total novice in c + embedded so I the learning curve is a bit high😅

**Comment by aseques** [comment]
There's a guide for the values in https://twitter.com/PabloFuente/status/1340958944072785921?s=19, ideally less than 500ppm, and no more than 800ppm.

**Comment by oskrs111** [comment]
I already have ordered a KY-012 Buzzer. As soon it arrives will work on the feature implementation 😉.

**Comment by oskrs111** [comment]
Buzzer support is already implemented, but note that because the operating voltage for KY-012 Buzzer module, an additional N-MOSFET is needed to activate. I have used a 2N7000 MOSFET but it is possible to use other with a suitable Gate voltage about 3V.
Check wiki for further details.
